input { 
  file {
    path => "/app/weblog.csv"
    start_position => "beginning"
  }
}

filter {
  csv {
     separator => ","
     skip_header => true
     columns => ["IP", "Time", "URL", "Status"]
}
  mutate {
     convert => {"Status" => "integer"}
     gsub => ["Time", "\[", ""]
}
  date {
    match => ["Time", "dd/MMM/yyyy:HH:mm:ss"]
    target => "event_timestamp"
    timezone => "UTC"
}
  if "_dateparsefailure" in [tags] {
    drop { }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "clickstream"
  }
  stdout { codec => rubydebug }
}
