input { 
  file {
    path => "/app/weblog.csv"
    start_position => "beginning"
  }
}

filter {
  csv {
     separator => ","
     skip_header => true
     columns => ["IP", "Time", "URL", "Status"]
}
  mutate {
     convert => {"Status" => "integer"}
     gsub => ["Time", "\[", ""]
}
  date {
    match => ["Time", "dd/MMM/yyyy:HH:mm:ss"]
    target => "@timestamp"
    timezone => "UTC"
}
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "clickstream"
  }
  stdout { codec => rubydebug }
}
